CREATE DATABASE TURISMO;
USE TURISMO;


CREATE TABLE PAIS ( 
	COD_PAIS INT PRIMARY KEY , 
	NOM_PAIS VARCHAR (30)
	);
	
INSERT INTO PAIS (COD_PAIS,NOM_PAIS) VALUES (1,'Brasil');

CREATE TABLE ESTADO (
	COD_ESTADO INT PRIMARY KEY , 
	NOM_ESTADO VARCHAR (30), 
	COD_PAIS INT,
	FOREIGN KEY (COD_PAIS) REFERENCES PAIS (COD_PAIS)
	);
-- COD_PAIS REFERENCIA PAIS

INSERT INTO ESTADO (COD_ESTADO,NOM_ESTADO,COD_PAIS) VALUES (1,'São Paulo', 1);

CREATE TABLE CIDADE (
	COD_CIDADE INT PRIMARY KEY, 
	NOM_CIDADE VARCHAR(30), 
	COD_ESTADO INT,
	FOREIGN KEY (COD_ESTADO) REFERENCES ESTADO (COD_ESTADO)
	);
-- COD_ESTADO REFERENCIA ESTADO

INSERT INTO CIDADE(COD_CIDADE,NOM_CIDADE,COD_ESTADO) VALUES (1,'Osasco',1);

CREATE TABLE BAIRRO ( 
	COD_BAIRRO INT PRIMARY KEY , 
	NOM_BAIRRO VARCHAR (30), 
	COD_CIDADE INT,
	FOREIGN KEY (COD_CIDADE) REFERENCES CIDADE (COD_CIDADE)
	);
-- COD_CIDADE REFERENCIA CIDADE

INSERT INTO BAIRRO (COD_BAIRRO, NOM_BAIRRO, COD_CIDADE) VALUES (1,'Centro',1);

CREATE TABLE LOGRADOURO (
	CEP INT PRIMARY KEY, 
	DESC_LOG VARCHAR (40), 
	TIPO_LOG VARCHAR (15), 
	COD_BAIRRO INT,
	FOREIGN KEY (COD_BAIRRO) REFERENCES BAIRRO (COD_BAIRRO)
	);
-- COD_BAIRRO REFERENCIA BAIRRO

INSERT INTO LOGRADOURO (CEP,DESC_LOG,TIPO_LOG,COD_BAIRRO) 
	VALUES (111100,'Afongo Pignitari','Rua',1);
INSERT INTO LOGRADOURO (CEP,DESC_LOG,TIPO_LOG,COD_BAIRRO) 
	VALUES (5559911,'Amélia','Rua',1);

	
CREATE TABLE CLIENTES(
	COD_CLI INT PRIMARY KEY, 
	NOM_CLI VARCHAR (40), 
	IDADE_CLI INT,
	NUM_CLI INT,  
	COMP_CLI VARCHAR(10), 
	RG_CLI VARCHAR (15), 
	CPF_CLI VARCHAR(15), 
	EST_CIV_CLI VARCHAR (10), 
	SEXO_CLI VARCHAR (10),
	CEP INT,
	FOREIGN KEY (CEP) REFERENCES LOGRADOURO (CEP)
	);
-- CEP REFERENCIA LOGRADOURO
INSERT INTO CLIENTES(COD_CLI,NOM_CLI,IDADE_CLI,NUM_CLI,COMP_CLI,RG_CLI,CPF_CLI,EST_CIV_CLI,SEXO_CLI,CEP)VALUES(10,'João da Silva',25, 100, 'Ap 12','12345678','33311122288','Casado','Masculino', 111100);

INSERT INTO CLIENTES (COD_CLI, NOM_CLI,IDADE_CLI,NUM_CLI,COMP_CLI,RG_CLI,CPF_CLI
,EST_CIV_CLI,SEXO_CLI,CEP) VALUES(11,'Elvis Presley',30, 155, NULL,'88811100',
'123777111','Casado','Masculino', 5559911);


CREATE TABLE COMPANHIA (
	COD_COMP INT PRIMARY KEY ,  
	NOM_COMP VARCHAR (20)
	);
	
INSERT INTO COMPANHIA (COD_COMP,NOM_COMP)VALUES(155,'GOL');

CREATE TABLE AVIOES (
	COD_AVI INT PRIMARY KEY , 
	MOD_AVI VARCHAR (20) , 
	CAP_AVI INT , 
	COD_COMP INT,
	FOREIGN KEY (COD_COMP) REFERENCES COMPANHIA (COD_COMP)
	);
-- COD_COMP REFERENCIA COMPANHIA
INSERT INTO AVIOES(COD_AVI,MOD_AVI,CAP_AVI,COD_COMP)VALUES(133,'Boeing 777',400,155);

CREATE TABLE VOOS (
	COD_VOO INT PRIMARY KEY , 
	ORI_VOO VARCHAR (20), 
	DEST_VOO VARCHAR (20) , 
	DATA VARCHAR (10),
	HORA VARCHAR(5),
	COD_AVI INT,
	FOREIGN KEY (COD_AVI) REFERENCES AVIOES (COD_AVI)
	);
-- COD_AVI REFERENCIA AVIOES
INSERT INTO VOOS(COD_VOO,ORI_VOO,DEST_VOO,DATA,HORA,COD_AVI)VALUES(100,'São Paulo',
'Londres','07042018','1510',133);

CREATE TABLE TRIPULACAO_VOO( 
	COD_TRIP INT PRIMARY KEY, 
	NOM_TRIP VARCHAR (60),
	COD_VOO INT ,
	FOREIGN KEY (COD_VOO) REFERENCES VOOS (COD_VOO)
	);
-- COD_VOO REFERENCIA VOOS
INSERT INTO TRIPULACAO_VOO(COD_TRIP,NOM_TRIP,COD_VOO) VALUES(20,'Maria Santos',100);

CREATE TABLE CLIENTE_VOO(
	COD_CLI INT , 
	COD_VOO	INT,
	POLT VARCHAR (5),
	FOREIGN KEY (COD_CLI) REFERENCES CLIENTES (COD_CLI),
	FOREIGN KEY (COD_VOO) REFERENCES VOOS (COD_VOO)
	);
-- COD_CLI REFERENCIA CLIENTES
-- COD_VOO REFERENCIA VOOS
INSERT INTO CLIENTE_VOO(COD_CLI,COD_VOO,POLT)VALUES(10,100,'10A');

--*6.	Dê um exemplo de: 
--•	Consulta com BETWEEN 

SELECT * FROM CLIENTE_VOO WHERE (COD_VOO) BETWEEN 10 AND 50;

--•	Consulta com IN 
SELECT * FROM TRIPULACAO_VOO WHERE (COD_VOO) IN (10,100);

--•	Consulta com LIKE 
SELECT * FROM VOOS WHERE (DEST_VOO) LIKE 'Londres';

--•	Exclusão com NOT BETWEEN 
DELETE FROM TRIPULACAO_VOO WHERE (COD_TRIP) NOT BETWEEN 0 AND 10;

--•	Alteração com NOT IN 
UPDATE CLIENTES SET NOM_CLI='Michael Jackson' where (COD_CLI) = 10;
--•	Alteração com NOT LIKE
UPDATE CLIENTES SET IDADE_CLI=50 WHERE (NOM_CLI) NOT LIKE 'Michael Jackson';

